spring.datasource.hikari.maximum-pool-size=20

app.admin.enabled=false

logging.level.com.icet.carrental=INFO
logging.level.org.springframework.jdbc=WARN
logging.level.org.springframework.security=WARN

management.endpoints.web.exposure.include=health
